tag:
  - ai2_arc
dataset_path: allenai/ai2_arc
task: arc_challenge_cot
dataset_name: ARC-Challenge
output_type: generate_until
training_split: train
validation_split: validation
test_split: test
doc_to_text: !function util.doc_to_text_cot
doc_to_target: "({{answerKey}})"
generation_kwargs:
  until:
    - "</s>"
    - "\n"
    - "<|im_end|>"
  do_sample: true
  temperature: 0.5
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "((?<=The answer is )(.*)(?=.)|(?<=answer is )(.*)(?=.)|(?<=The answer: )(.*)(?=.)|(?<=The final answer: )(.*)(?=.))"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(\\([A-Z]\\))"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0


