task: winogrande_generate
dataset_path: allenai/winogrande
dataset_name: winogrande_xl
output_type: generate_until
training_split: train
validation_split: validation
doc_to_text: !function preprocess_winogrande.doc_to_text
doc_to_target: !function preprocess_winogrande.doc_to_target
generation_kwargs:
  until:
    - "</s>"
    - "\n"
    - "<|im_end|>"
  do_sample: true
  temperature: 0.5
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "((?<=The answer is )(.*)(?=.)|(?<=answer is )(.*)(?=.)|(?<=The answer: )(.*)(?=.)|(?<=The final answer: )(.*)(?=.))"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(\\([A-Z]\\))"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
