task: hellaswag_cot
dataset_path: Rowan/hellaswag
dataset_name: null
output_type: generate_until
training_split: train
validation_split: validation
test_split: null
process_docs: !function utils.process_docs
doc_to_text: "{{query}}\nChoose the best continuation:\n\n(A) {{choices[0]}}\n(B) {{choices[1]}}\n(C) {{choices[2]}}\n(D) {{choices[3]}}\nLet's think step by step."
doc_to_target: "{{['(A)', '(B)', '(C)', '(D)'][gold]}}"
generation_kwargs:
  until:
    - "</s>"
    - "\n"
    - "<|im_end|>"
  do_sample: true
  temperature: 0.5
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "((?<=The answer is )(.*)(?=.)|(?<=answer is )(.*)(?=.)|(?<=The answer: )(.*)(?=.)|(?<=The final answer: )(.*)(?=.))"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(\\([A-Z]\\))"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
