task: truthfulqa_generative
dataset_path: truthfulqa/truthful_qa
dataset_name: multiple_choice
output_type: generate_until
training_split: null
validation_split: validation
test_split: null
num_fewshot: 0
doc_to_text: !function util.doc_to_text_gen
doc_to_target: !function util.doc_to_target
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "(?<=The answer is )(.*)(?=.)"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(\\([0-9]\\))"
      - function: "take_first"
metadata:
  version: 2.0
